# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20170905_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
