# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
    ]
